export const AUTHTOKEN = 'x-auth-token'
export const PROJECT_NAME = 'envoix'
export const CONFIG_FILE = 'env-config.json'
export const SERVER_URL = 'http://localhost:8000'
export const ORIGIN = 'envoix-cli'
